server:
  port: 8085
spring:
  kafka:
    consumer:
      group-id: "dealGroup"
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:postgresql://localhost:5432/credit-db
    username: fakeuser
    password: fakepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc.time_zone: UTC
  liquibase:
    change-log: db/changelog/changelog-master.xml

springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true

integration:
  calculator:
    base-url: http://localhost:8190
    method:
      url-offer: /calculator/offers
      url-calc: /calculator/calc
