server:
  port: 8205
springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true
integration:
  deal:
    base-url: http://localhost:8085
    post-method:
      path-select-offer: /deal/offer/select
      path-statement: /deal/statement
