server:
  port: 8190
springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true
initialization:
  interest-rate: ${INITIALIZATION_INTEREST_RATE}
  insurance-rate: ${INITIALIZATION_INSURANCE_RATE}

